---
jobs:

## Based on the steps documented here: https://kubernetes.io/docs/setup/custom-cloud/kops/
- name: create-route53
  plan:
  - get: git-repository
    trigger: true
  - put: tf-route53
    params:
    - env_name: route53


# ========================= Resource Types =========================
resource_types:

- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest


# ============================ Resources ============================

resources:
- name: git-repository
  type: git
  source:
    uri: ((git_repository))
    branch: master

- name: tf-route53
  type: terraform
  source:
    terraform_source: git-repository/terraform/concourse/terraform/route53
    storage:
      storage:
        bucket: ((ci_bucket_region))
        bucket_path: terraform/
        access_key_id: {{s3.access_aws_access_key_id}}
        secret_access_key: {{s3.aws_secret_access_key}}
    env:
        AWS_ACCESS_KEY_ID: {{full.access_aws_access_key_id}}
        AWS_SECRET_ACCESS_KEY: {{full.aws_secret_access_key}}

# - name: deploy-trigger
#   type: semver
#   source:
#     initial_version: 0.0.0
#     driver: s3
#       region_name: ((ci_bucket_region))
#       access_key_id: ((s3.access_aws_access_key_id))
#       secret_access_key: ((s3.aws_secret_access_key))
#       server_side_encryption: AES256
#     bucket: ((ci_bucket))
#     key: ci/trigger


