---
jobs:


- name: setup
  plan:
  - aggregate:
    - task: create-ci-bucket
      config:
        platform: linux
        image_resource: 
          type: docker-image
          source:
            repository: ((awscli_image))
        run:
          path: /bin/sh
          args:
            - -c
            - |
                aws s3 mb s3://((ci_bucket))
        params:
            AWS_ACCESS_KEY_ID: ((s3access_aws_access_key_id))
            AWS_SECRET_ACCESS_KEY: ((s3access_aws_secret_access_key))
            AWS_DEFAULT_REGION: ((ci_bucket_region))